"""As migrations precisam construir exatamente o schema dos modelos.

Sem este teste, `models.py` e `migrations/` divergem em silêncio e o erro só
aparece em produção.

**Isolamento.** Estes testes fazem `upgrade`/`downgrade` do schema inteiro,
então não podem compartilhar banco com o resto da suíte. Com SQLite isso é
grátis (um arquivo por `tmp_path`); com PostgreSQL é preciso criar um banco
descartável — caso contrário eles derrubam as tabelas debaixo dos outros
testes, que foi exatamente o que aconteceu na primeira corrida contra o
alvo real.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from pathlib import Path
from uuid import uuid4

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from factories import sync_url
from sqlalchemy import create_engine, inspect, text

PROJECT_ROOT = Path(__file__).resolve().parents[2]

EXPECTED_TABLES = {
    "agents",
    "goals",
    "agent_runs",
    "observations",
    "plans",
    "actions",
    "action_attempts",
    "episodes",
    "skills",
    "run_events",
    "plan_cache",
    "alembic_version",
}


@pytest.fixture
def migration_url(tmp_path) -> Iterator[str]:
    """URL de um banco descartável, exclusivo destes testes."""
    configured = os.environ.get("NEUROLOOP_TEST_DATABASE_URL")
    if not configured or "postgresql" not in configured:
        yield f"sqlite+aiosqlite:///{tmp_path / 'migrations-test.db'}"
        return

    nome = f"neuroloop_migtest_{uuid4().hex[:8]}"
    admin = create_engine(
        sync_url(configured).rsplit("/", 1)[0] + "/postgres",
        isolation_level="AUTOCOMMIT",
    )
    with admin.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{nome}"'))
    admin.dispose()

    try:
        yield configured.rsplit("/", 1)[0] + f"/{nome}"
    finally:
        admin = create_engine(
            sync_url(configured).rsplit("/", 1)[0] + "/postgres",
            isolation_level="AUTOCOMMIT",
        )
        with admin.connect() as conn:
            conn.execute(
                text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    f"WHERE datname = '{nome}' AND pid <> pg_backend_pid()"
                )
            )
            conn.execute(text(f'DROP DATABASE IF EXISTS "{nome}"'))
        admin.dispose()


@pytest.fixture
def alembic_config(migration_url, monkeypatch) -> Config:
    monkeypatch.setenv("NEUROLOOP_DATABASE_URL", migration_url)
    config = Config(str(PROJECT_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    return config


def _inspect(url: str):
    engine = create_engine(sync_url(url))
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_cria_todas_as_tabelas(alembic_config, migration_url):
    command.upgrade(alembic_config, "head")
    assert _inspect(migration_url) >= EXPECTED_TABLES


def test_migrations_nao_divergem_dos_modelos(alembic_config):
    """`alembic check`: qualquer drift entre models.py e migrations falha."""
    command.upgrade(alembic_config, "head")
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - só falha em drift
        pytest.fail(f"migrations divergiram dos modelos: {exc}")


def test_downgrade_remove_o_schema(alembic_config, migration_url):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    assert _inspect(migration_url) - {"alembic_version"} == set()
