"""Fronteira com o LLM. O núcleo conhece o protocolo, não o provider."""

from neuroloop.llm.client import (
    DEFAULT_MODEL,
    DELIBERATION,
    PRICING,
    PRICING_VERSION,
    SUMMARIZATION,
    LLMClient,
    LLMError,
    LLMResponse,
    LLMUsage,
    Message,
    ModelPricing,
    ModelProfile,
    compute_cost,
    usage_from_provider,
)
from neuroloop.llm.fake import FakeLLMClient, RecordedCall, RefusingLLMClient
from neuroloop.llm.schemas import (
    DecisionTranslationError,
    LlmActionProposal,
    LlmCommandExitCodeEquals,
    LlmCriterion,
    LlmDecision,
    LlmFileExists,
    LlmHttpStatusEquals,
    LlmJsonPathCount,
    LlmJsonPathEquals,
    LlmPlan,
    LlmPlanStep,
    to_action_proposal,
    to_criterion,
    to_decision,
    to_plan,
)

__all__ = [
    "DEFAULT_MODEL",
    "DELIBERATION",
    "PRICING",
    "PRICING_VERSION",
    "SUMMARIZATION",
    "DecisionTranslationError",
    "FakeLLMClient",
    "LLMClient",
    "LLMError",
    "LLMResponse",
    "LLMUsage",
    "LlmActionProposal",
    "LlmCommandExitCodeEquals",
    "LlmCriterion",
    "LlmDecision",
    "LlmFileExists",
    "LlmHttpStatusEquals",
    "LlmJsonPathCount",
    "LlmJsonPathEquals",
    "LlmPlan",
    "LlmPlanStep",
    "Message",
    "ModelPricing",
    "ModelProfile",
    "RecordedCall",
    "RefusingLLMClient",
    "compute_cost",
    "to_action_proposal",
    "to_criterion",
    "to_decision",
    "to_plan",
    "usage_from_provider",
]
